# Note that when run on AzureML, train_dir and val_dir are relative to the input Azure Blob Storage container, and
# out_dir is relative to the output container. When run locally, all paths are relative to the project root.
train_dir: ./v1.4/1000hrs/train
val_dir: ./v1.4/1000hrs/val
out_dir: ./

train_set_cfg:
  sample_frac: 1.0
  max_urls: null  # null means no limit
val_set_cfg:
  sample_frac: 1.0
  max_urls: null  # null means no limit

log_params_mlflow: True
log_metrics_mlflow: True

scheduler_step_every: [1, iterations]
scheduler_name: step_lr
scheduler_linear_warmup_decay_cfg:
  warmup: 10000
  decay: 260000
scheduler_step_lr_cfg:
  # Decay LR by a factor of 0.1 after 200k iterations
  step_size: 200000
  gamma: 0.1

stop_after: [260000, iterations]
eval_every: [1000, iterations]
save_every: [1000, iterations]

global_batch_size: 256
learning_rate: 1e-5
weight_decay: 1e-2  # according to the paper set to 1e-2

# Large model per CSS with Conformer definition
conformer_css_cfg:
  nnet_conf:
    conformer_conf:
      attention_dim: 512  # default 256
      attention_heads: 8  # default 4
      num_blocks: 18  # default 16
