# * Key-value pairs that do not appear here will be set to default values defined in the dataclasses.
# * Key names and value types will be verified.

asr:
  model_name: 'large-v2'

css:
  # css will pass through mic0 in MC sessions and the channel as is in SC sessions
  pass_through_ch0: True
  segment_size: 3.
  hop_size: 1.5
  device: "cuda:0"
  show_progressbar: True

diarization:
  method: 'word_nmesc'     # choose from "nmesc" and "nmesc_msdd"
  min_embedding_windows: [3.0,2.5,2.0,1.5,1.0,0.5]
  embedding_model_name: "titanet_large"
  msdd_model_name: "diar_msdd_telephonic"
  # vad_model_name: "vad_telephony_marblenet"    # for 8kHz telephone
  vad_model_name: "vad_multilingual_marblenet"   # for 16kHz



# one MC session:
#session_query: 'device_name == "rockfall_0" and is_mc == True and meeting_id == "MTG_30830"'

# one SC session:
#session_query: 'device_name == "plaza_0" and is_mc == False and meeting_id == "MTG_30830"'

# all sessions:
session_query: null